# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20171218_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='webinar',
        ),
    ]
